version: "3.9"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: ryan
    # - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net

  # backend:

  # frontend:

volumes:
  data:
